### ISSUE TITLE
Generate more statistics

### ISSUE THREAD

**Issue by ErikBjare** [minriksdag/minriksdag.github.io#15]
- Hur olika partier röstat i olika nyckelfrågor. 
   - Vilka nyckelfrågor?
 - Vilka ledamöter/partier är mest frånvarande? 
   - Vilka brukar avstå/hålla med/rösta mot?
 - Hur påverkar ålder/kön vad man röstar?
 - Vilka län är de olika partiernas ledamöter från?
 - Vem har suttit i riksdagen längst? Vilka är nya till riksdagen?

**Comment by byv14ahi** [comment]
Förslag på nyckelfrågor:
Misstroendeomröstning Peter Hulqvist efter IT-skandalen, röstades 2017-09-15
Värnplikt återinförs, röstades 2 mars 2017 (SOU 2016:63)
Antalet dagar som inte kan överlåtas till den andra föräldern från 60 till 90 dagar.  28 maj 2015 (Prop. 2014/15:124)
Skärpt exportkontroll av krigsmateriel. Röstades 28 februari 2018. 2017/18:UU9
